modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''新增两只爆炸系敌对生物：苦力怕幻翼（俯冲击中玩家即在命中点引爆苦力怕级爆炸）与苦力怕海豚（高速撞船、贴身自爆、上岸突袭）。两只都能像原版苦力怕一样被闪电充能，威力翻倍。'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
